### PR TITLE
Weather app new Version 2.0

### PR DESCRIPTION
**Pull request by MAYANK816**
I have Introduced some new features in the app and some UI fixes.

### CODE REVIEW

**Comment by MAYANK816** [comment]
Please help me to resolve this issue.

**Comment by Mridul2820** [comment]
Hi @MAYANK816 let me help you on this

In the `README.md` 
Add your details after this line(at line number 69)
```
| Meme generator   | [Demo](https://meme-generator-smoky.vercel.app/)  | [Source Code](/projects/javascript/meme-generator)    | [vidhanshu](https://github.com/vidhanshu)
```
And revert everything else in that file

**Comment by MAYANK816** [comment]
Thanks mate solved the conflicts

**Comment by Mridul2820** [comment]
Hi @MAYANK816 You have added my GitHub profile link in the readme. Please add your profile Link

Screenshot 2022-10-05 200705

**Comment by MAYANK816** [comment]
Changed in repo and readme of weather_app_new branch

**Comment by Mridul2820** [comment]
Thank you for contributing! 🚀

**Pull request merged**
