### PR TITLE
RGB quize added

### PR DESCRIPTION
**Pull request by vidhanshu**

### CODE REVIEW

**Comment by vidhanshu** [comment]
@Mridul2820  Now please do check if everything is fine!

**Comment by Mridul2820** [comment]
Hi @vidhanshu , You need to add your project details in the main `README.md` File

You can follow this Example: [example-readme-details](https://github.com/Mridul2820/Hacktoberfest2022/blob/master/CONTRIBUTING.md#example-readme-details)

**Comment by vidhanshu** [comment]
done !

**Comment by Mridul2820** [comment]
This `[Demo](https://github.com/vidhanshu/Hacktoberfest/tree/master/projects/javascript/rgb%20quize)` Link is working
Please provide a valid demo link

**Comment by vidhanshu** [comment]
@Mridul2820  Now is it okay?

**Comment by Mridul2820** [comment]
Thank you for contributing! 🚀

**Pull request merged**
